// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNtfCQvV5gUFB92L3dfnb9Tg7LqFZlP4',
    appId: '1:26422933770:web:4733a3e0b9ae6c124a22f3',
    messagingSenderId: '26422933770',
    projectId: 'first-f21d8',
    authDomain: 'first-f21d8.firebaseapp.com',
    storageBucket: 'first-f21d8.appspot.com',
    measurementId: 'G-W2LQKEJ649',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtNtJf4h8MmwL4DW8BQBT_Wq2_JSdLiXA',
    appId: '1:26422933770:android:37c40bea432ff6c44a22f3',
    messagingSenderId: '26422933770',
    projectId: 'first-f21d8',
    storageBucket: 'first-f21d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZgOlaONEDL8_KC_NqDe102WA4iMLEM7s',
    appId: '1:26422933770:ios:cd6a17d85782ee494a22f3',
    messagingSenderId: '26422933770',
    projectId: 'first-f21d8',
    storageBucket: 'first-f21d8.appspot.com',
    iosBundleId: 'com.satpura.hostel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZgOlaONEDL8_KC_NqDe102WA4iMLEM7s',
    appId: '1:26422933770:ios:cd6a17d85782ee494a22f3',
    messagingSenderId: '26422933770',
    projectId: 'first-f21d8',
    storageBucket: 'first-f21d8.appspot.com',
    iosBundleId: 'com.satpura.hostel',
  );
}
